### ISSUE TITLE
Use this library in my app

### ISSUE THREAD

**Issue by hubunion** [ILikeYourHat/Kudoku#53]
I want to use this library in my app.

**Comment by ILikeYourHat** [comment]
Sure, feel free to do so 😀 Let me know if you would need any additional
features or changes to the library

czw., 19 gru 2024, 02:59 użytkownik hubunion ***@***.***>
napisał:

**Comment by ILikeYourHat** [comment]
Closing the issue for now. I you would have any question, bug or feature request, please create a separate issue for each of them
